sudo: false

language: node_js

node_js:
  - node

install: npm install

script:
  - npm test

before_script :
    - npm run lint

after_script :
  - npm install coveralls && npm run coverage

notifications:
  email: false